export {
  DEFAULT_BASE_SALARY_IDR,
  DEFAULT_KASBON_AMOUNT_IDR,
  DEFAULT_MENU_PRICE_IDR,
  DEFAULT_MIN_STOCK_ALERT,
  DEFAULT_GEOFENCE_RADIUS_METERS,
  DEFAULT_BRANCH_GEOFENCE_RADIUS_METERS,
  DEFAULT_LATE_PENALTY_PER_MINUTE_IDR,
  DEFAULT_OVERTIME_PAY_PER_HOUR_IDR,
  DEFAULT_MIN_OVERTIME_THRESHOLD_MINUTES,
  DEFAULT_SUBSCRIPTION_PRICE_IDR,
  DEFAULT_GRACE_PERIOD_DAYS,
} from '@precis/shared-utils';
